apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace-config.yaml
  - 02-rbac.yaml
  - 03-deployment-service.yaml

commonLabels:
  app.kubernetes.io/name: kubernetes-mcp
  app.kubernetes.io/part-of: kubernetes-mcp